### ISSUE TITLE
Angular 2, Visual Studio 2015, ASP 5 - 'System' is Undefined, 'Require' is Undefined

### ISSUE THREAD

**Issue by phunik** [mithunvp/ng2Mvc5Demo#3]
I am attempting to get the Quick Start to run in Visual Studio 2015. The problem I am getting is when I run it as it with this piece of code in system.config.js:
(function (global) {
    System.config({
 
'System' is Undefined, 'Require' is Undefined

**Comment by robvon** [comment]
This is a symptom of not running the Gulp task me thinks. Instructions to do so are buried near the bottom of the author's blog. It is not clear why we should only execute "default"... anyway this is the extract:

"Now that we are almost done, we need to run GULP tasks so that Angular 2 files, TS files are moved to appropriate folder. **Open Task Runner Explorer in Visual Studio 2015 and run default task shown.**..."

**Comment by ghost** [comment]
You need to follow the steps in the README.md file!

**Comment by binfask** [comment]
i am getting the same error on production.
